.github/docs/AI_Research_Notes.md
Adding a summary of the research done into selecting an LLM.
Fixes # LINKTA-71
Please delete options that are not relevant.
No tests needed for documentation.
Before submitting your pull request, please review the following checklist:
None
=> LINKTA-71 Document AI research

.github/docs/SECURITY_BEST_PRACTICES.md
This PR introduces a new markdown file, `SECURITY_BEST_PRACTICES.md` under `/docs`, dedicated to outlining security best practices for our development teams. 
- **Frontend Security**: XSS protection, CSRF protection, data handling and storage, HTTP headers, API security, dependency management, and build & deployment practices.
- **Backend Security**: Authentication, session management, input validation and sanitization, database security, access control, infrastructure, and error handling and logging.
- **General Security Practices**: Code reviews and training, encryption and data protection, access control, compliance and audits.
Fixes #[Linkta-87](https://linkta.atlassian.net/browse/LINKTA-87?atlOrigin=eyJpIjoiMjg5YjZkZGMyY2JlNGQ3YTlmYzUzYzczOTQxYTMxMGIiLCJwIjoiaiJ9)
Please delete …
=> Proposal for Security Best Practices Documentation 

package-lock.json, package.json
- Uninstall next & dependencies
- Install react-router & dependencies
Fixes #[LINKTA-114](https://linkta.atlassian.net/browse/LINKTA-114)
- Update scripts in package.json when build tool is added & configured
- Add build tool & dependencies
- Build tool config
[LINKTA-114]: https://linkta.atlassian.net/browse/LINKTA-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LINKTA-114: Uninstall Next.js and install React Router

client/App.jsx, client/index.html, client/main.jsx, client/package-lock.json, client/package.json, client/vite.config.js
I moved index.html from public to client since vite is very particular about where to find the index.html file. Also created App and main components to test if vite will bundle correctly.
=> set up vite config in client folder

.eslintrc.json, .prettierignore, .prettierrc.json
Fix the prettier single quotes inconsistency. 
Removed the prettier overrides in eslintrc.json to keep .prettierrc.json as the source of truth for prettier. 
Added ignore file for prettier to ignore node_modules
Fixes # (issue) 38: https://github.com/Linkta-org/core/issues/38
=> Fix: Bug 38 - prettierrcjson is configured to use double quotes over single quotes

client/components/layout/main-layout/MainLayout.tsx
Set up the basic structure for MainLayout, ensuring it can wrap around other page components effectively.
Fixes #[Linkta 131](https://linkta.atlassian.net/browse/LINKTA-131?atlOrigin=eyJpIjoiN2FjZWY1ZDA1YWU0NGMwNjhiOWZiMGQwNTA1ZWJhNTMiLCJwIjoiaiJ9)(issue)
- Styling & robust testing yet to be completed
- Prop added to allow the Footer to show only on certain pages
=> LINKTA-131: Create MainLayout Component Structure

tsconfig.json
PR #41 was missing a change. I'm not sure how I missed that the baseUrl and paths were missing from the tsconfig.
Fixes # (issue)
Retested with manual code. `npm run dev` works, but I thought it did before as well.
=> LINTKA-169: adding missing baseUrl and paths to tsconfig.

server/models/NodeModel.ts, server/models/UserModel.ts, server/types/datamodels.d.ts
Fixing linting issue, double quotes to single quotes
Fixes # (issue)
- [ X]  🐛 Bug fix (non-breaking change which fixes an issue)
N/A
=> Linkta 176: linting rule update creates multiple downstream changes

.github/docs/Setting_Up_Zustand_Stores.md
- Added `Setting_Up_Zustand_Stores.md` doc to create example Zustand store and set some best practices for state management with Zustand
=> LINKTA-142 Setup Zustand

.github/docs/HOW_TO_OBTAIN_GEMINI_KEY.md
Documentation for obtaining a Gemini key for use during development.
Linking Issues:
- To associate this pull request with a GitHub issue within the same repository, use the "Fixes #IssueNumber" syntax.
- For external issues, use Markdown links: [Issue Name](Issue Link).
-->
Fixes # (issue) 
Not applicable here
=> Linkta 157 darren to document process for getting api key

.github/decisions/Decision_Documentation_Template.md
Create a template for documentation of our research/decisions
Fixes # (issue) 162
=> LINKTA-162: docs: Create basic template for writing research or decision documentation

.github/PULL_REQUEST_TEMPLATE.md
- fixes broken links to security best practices & naming conventions .md files 
Fixes # [58](https://github.com/Linkta-org/core/issues/58)
=> LINKTA-198 Broken Links: Security Best Practices Document & Naming Conventions Guide in PR template

client/main.tsx, package-lock.json, package.json
Added React Query to frontend to be used.  Initialized it with the defaults and added DevTools to be used for getting query info easily.  DevTools is initially closed and can be opened by clicking the button on the lower right of the client when running it.
Fixes # (issue)
=> Initialized React Query for the Frontend

client/components/common/PromptInputForm.tsx, client/features/prompt-input-page/PromptInputPage.tsx, client/features/prompt-input-page/components/PromptInputBox.tsx, client/features/prompt-input-page/components/PromptInputField.tsx
- delete PromptInputField component
- rename PromptInputBox to PromptInputForm
- update PromptInputForm code to match new name
- move PromptInputForm to common components directory
- import PromptInputForm to PromptInputPage
- update PromptInputPage placeholder element
=> LINKTA-44 Implement PromptInputPage

.github/decisions/Tree_Visualisation_UI_Library_Decision_Log.md
Following our discussion on Friday, this proposal outlines our decision to integrate React Flow and dagre for our tree visualization feature. This selection is aimed at optimizing user interaction and rendering performance while ensuring seamless integration with our existing React-based tech stack.
**Key Highlights:**
- **Compatibility**: Ensures seamless integration with React, TypeScript, Zustand, and React Query. Prepared for both web and mobile platforms, aligning with our strategic future expansion.
- **User Experience**: Chosen for superior interactivity, including drag-and-drop and editing functionalities, ensuring an intuitive UI.
- **Efficiency**: Balances dynamic layout capabilities with manageable bundle sizes and accessible documentation, promoting rapid, within-budget …
=> Documentation/linkta 252 create tree visualization UI library decision log

.github/decisions/End_to_End_Testing_Decision_Log.md
Select an end-to-end testing framework.
Recommendation: Cypress
Fixes #273
=> Add Decision Log for End to End Testing Framework

.github/docs/HOW_TO_RUN_CYPRESS_E2E_TESTS.md
Add instructions for running Cypress E2E tests in the `landing-page` repository.
Fixes # 274
- Verified that the preview of the instructions is displayed as expected.
=> Add Instructions for Running Cypress E2E Tests

client/main.tsx, package-lock.json, package.json
Install MUI Core, Emotion, MUI Icons, and Roboto font.
Fixes # (issue)
=> Added Material UI and related dependencies; added Roboto font import

server/controllers/userInputController.ts, server/models/UserInputModel.ts, server/routes/userInput.ts
Adds userInputController and userInput route
Fixes #86
=> implements userInputController and userInput route

.github/docs/API_DESIGN_DOCUMENTATION_V1.md, mocks/index.ts, mocks/userId.ts, package.json, server/controllers/userInputController.ts, server/models/UserInputModel.ts, server/models/UserModel.ts, server/routes/userInput.ts, server/types/datamodels.d.ts, tsconfig.json
- Created a new route in the backend API to handle the retrieval of all related UserInput.
- Implemented the logic to retrieve all related UserInput from the database & return the retrieved UserInput data as `{"userInputs": [array of UserInputs]}` from the API.
- Added a `/mocks` folder to store mock data.
- Added NODE_ENV to scripts for consistent environment settings.
Fixes #152
=> 152 implement api endpoint for retrieving user input history

client/vite.config.js, package-lock.json, package.json, tsconfig.json
This PR adds two Vite plugins aimed at improving the frontend developer experience.
[Unplugin Turbo Console](https://github.com/unplugin/unplugin-turbo-console) adds some color and style to console.logs in the browser.
[Vite Plugin Checker](https://github.com/fi3ework/vite-plugin-checker) watches for TypeScript errors and logs a detailed report in the dev terminal. There is a browser modal which shows the same information, but I have disabled it as I found it intrusive.
In addition, ENV variables have been removed from the npm scripts invoked via `npm run dev`. The implementation was Unix-specific and broke the scripts for Windows users. Rather than add duplicate scripts or add dependencies to manage this issue, we can simply remove the variables and eliminate the issue. These ENV …
=> Added Turbo Console; Added Vite Plugin Checker; removed ENV variables from npm scripts

client/stores/LinktaFlowStore.ts, client/stores/UserInputStore.ts, client/types/LinktaFlow.ts, client/types/UserInput.ts, package.json
Minimal Zustand stores for immediate use.
Fixes #132
=> Simple Zustand stores for UserInput and LinktaFlow

server/controllers/linktaFlowController.ts, server/routes/linktaFlowRouter.ts, server/server.ts
Implemented functionality for fetching all LinktaFlows based on a specific users as well as fetching, updating, and deleting individual LinktaFlows.
Fixes #122 and #129  
Each endpoint has been tested using Postman, including intentionally triggering errors.
=> implement linktaFlow functionality

.github/docs/assets/api-design-flowchart-source-code.md
- Updated API design diagram
- Updated source code for diagram
Fixes #189
=> Updated api design flowchart png & source code

.github/docs/API_DESIGN_DOCUMENTATION_V1.md, .github/docs/assets/api-design-flowchart-source-code.md, server/middleware/validationMiddleware.ts, server/models/UserInputModel.ts, server/routes/linktaFlowRouter.ts, server/routes/userInput.ts, server/utils/helpers.ts
- Created a validation middleware to handle req validation
Subtask for #158
=> Implemented validation middleware

client/components/layout/UserInputList.tsx, client/hooks/useInputHistory.ts, mocks/userInputList.ts, server/controllers/userInputController.ts, server/models/UserInputModel.ts, server/types/datamodels.d.ts
- Updated UserInputSchema according to updated data design & associated implementation in app
Fixes #178
=> Updated userinputschema & associated implementation

.github/decisions/Rate_Limiting.md
This PR adds a spike in the decision docs for a rate limiting implementation ini Linkta
Fixes #165 
- [x ] 📝 Documentation update
Read the changes. Add comments and/or suggestions
=> Rate Limiting Spike for Discussion

client/components/layout/UserInputList.tsx, client/services/userInputService.ts
Implements functionality to the delete buttons associated with each user input in the sidebar.
Fixes #265
Run the application, navigate to the sidebar and click the delete button next to each user input in the sidebar to remove them. Verify the changes by checking the MongoDB database to confirm that each deleted item is removed. Observe the UI to ensure that the user input is immediately removed from the sidebar upon deletion and that the remaining inputs remain functional without any unintended changes.
=> Implement delete functionality for delete button on the operations menu

client/components/layout/UserInputList.tsx, client/features/output-visualization-page/OutputVisualizationPage.tsx, client/features/output-visualization-page/components/Flow.tsx, client/features/output-visualization-page/components/LinktaNode.tsx, client/hooks/useFetchLinktaFlow.ts, client/hooks/useInfiniteInputQuery.ts, client/routes/privateRoutes.tsx, client/services/userInputService.ts, server/server.ts
- API function for fetching LinktaFlow is created
- React Query hook for fetching LinktaFlow is implemented
Fixes #251
Flow component inside OutputVisualizationPage
Temp solution since LinktaFlowController currently doesn't accept a userInputId (will be fixed in #233)
1. At root dir, run `npm run dev`
2. Go to server -> controller -> LinktaFlowController
3. On the first line inside 'fetchLinktaFlow' method, add `console.log('hello')`
4. Click a tab on the sidebar
1. View page path changed to /output/:userInputId
2. 'hello' is logged in the terminal
Snackbar notification will be implemented in #247
=> implemented react query for fetching linktaflow
